#ifndef HUMAN_MACHINE_INTERFACE_H
#define HUMAN_MACHINE_INTERFACE_H

#define START "INIZIO"
#define PARKING "PARCHEGGIO"
#define STOP "ARRESTO"

#define HUMAN_MACHINE_INTERFACE_ERROR_LOGFILE "hmi.eLog"

#endif